version: '3.7'

services:

  db:
    image: postgres:14
    container_name: demo_app_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
        - "5432:5432"
    networks:
      - demo-db
networks:
  demo-db:
    driver: bridge